baseURL = 'https://moto6.github.io/blog/'
title = 'tech blog'
publishDir = "docs"
languageCode = 'en-us'
# languageCode = "ko-KR"
theme = 'hugo-liftoff'
googleAnalytics = "UA-XXXXXXXX-X"
paginate = 7

[author]
    name = '김동훈'
    email = 'ultraraptor@naver.com'

[params]
    Subtitle = 'techlog'
    description = 'techlog'
    commentoEnable = true
    AuthorName = '김동훈'
    GitHubUser = 'moto6'
    SidebarRecentLimit = 5

[permalinks]
  posts = '/:title/'