baseURL = 'https://moto3z.github.io/blog/'
title = 'tech blog'

languageCode = 'en-us'
# languageCode = "ko-KR"
theme = 'ananke'
googleAnalytics = "UA-XXXXXXXX-X"
paginate = 7

[author]
    name = '김동훈'
    email = 'ultraraptor@naver.com'

[params]
    Subtitle = '장잉정신 엔지니어링'
    description = '장잉정신 엔지니어링'
    commentoEnable = true
    AuthorName = '김동훈'
    GitHubUser = 'moto3z'
    SidebarRecentLimit = 5

[permalinks]
  posts = '/:title/'